accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("", views.CalendarViewNew.as_view(), name="calendar"),
    path("calendar/", views.CalendarViewNew.as_view(), name="calendar"),
    # path("calendars/", views.CalendarView.as_view(), name="calendars"),     delete later
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('next_week/<int:event_id>/', views.next_week, name='next_week'),
    path('next_day/<int:event_id>/', views.next_day, name='next_day'),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
    # path('new_project/',views.ProjectCreateView.as_view() , name='new_project'),
   
]

project_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import DashboardView, ProfileView, UpdateProfileView, ProjectCreateView
from calendarapp.views import other_views
from calendarapp.views.other_views import CalendarView




urlpatterns = [
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('new_project/', ProjectCreateView.as_view(), name='new_project'),
    path('add_project/', other_views.add_project, name='add_project'),
    path('add_project/add_task', other_views.add_task, name="add_task"),    
    path('edit_project/<int:project_id>/', other_views.edit_project, name='edit_project'),
    path('delete_project/<int:project_id>/', other_views.delete_project, name='delete_project'),
    path('projects/', other_views.list_user_projects_and_tasks, name='list_user_projects_and_tasks'),
    path('projects/add_task/<int:project_id>/', other_views.add_task, name='add_task'),
    path('projects/edit_task/<int:task_id>/', other_views.edit_task, name='edit_task'),
    path('projects/delete_task/<int:task_id>/', other_views.delete_task, name='delete_task'),
    path('tasks/toggle/<int:task_id>/', other_views.toggle_task_completion, name='toggle_task_completion'),
    path('create_project_from_template/', other_views.create_project_from_template, name='create_project_from_template'),
    path('projects/add/', other_views.add_project, name='add_project'),
    # path('projects/<int:project_id>/save_as_template/', other_views.create_template_from_project, name='create_template_from_project'),
    # path('calendarView/', CalendarView.as_view, name='calendarView'),
    path('data/', other_views.templates_data, name='templates_data'),
    path('project/<int:project_id>/save_as_template/', other_views.save_project_as_template, name='save_project_as_template'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <!-- <meta property="og:description" content="Event Dashboard" /> -->
        <title>{% block title %}{% endblock title  %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Main CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
        <!-- Just added for the modal-->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"> -->
        <!-- Font-icon css-->
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
        {% block extracss %}
        {% endblock extracss %}
    </head>
    {% if messages %}
        <div aria-live="polite" aria-atomic="true" style="position: relative;">
            <div style="position: absolute; top: 0; right: 0;">
                {% for message in messages %}
                    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000" style="margin-top: 1rem;">
                        <div class="toast-header">
                            <strong class="mr-auto">Message</strong>
                            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="toast-body">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <body class="app sidebar-mini">
        <!-- Navbar-->
        <header class="app-header">
            <!-- <a  href="{% url 'dashboard' %}"><h1>Project Planner</h1></a> will do this later -->
            <!-- Sidebar toggle button-->
            <a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
            <!-- Navbar Right Menu-->
            <ul class="app-nav">
                <li class="app-search">
                    <input class="app-search__input" type="search" placeholder="Search" />
                    <button class="app-search__button"><i class="fa fa-search"></i></button>
                </li>
                <!--Notification Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><i class="fa fa-bell-o fa-lg"></i></a>
                    <ul class="app-notification dropdown-menu dropdown-menu-right">
                        <!-- <li class="app-notification__title">You have 4 new notifications.</li> -->
                        <div class="app-notification__content">
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <!-- <p class="app-notification__message">Lisa sent you a mail</p>
                                        <p class="app-notification__meta">2 min ago</p> -->
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <!-- <p class="app-notification__message">Mail server not working</p>
                                        <p class="app-notification__meta">5 min ago</p> -->
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="app-notification__item" href="javascript:;">
                                    <span class="app-notification__icon">
                                        <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                    </span>
                                    <div>
                                        <!-- <p class="app-notification__message">Transaction complete</p>
                                        <p class="app-notification__meta">2 days ago</p> -->
                                    </div>
                                </a>
                            </li>
                            <div class="app-notification__content">
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <!-- <p class="app-notification__message">Lisa sent you a mail</p>
                                            <p class="app-notification__meta">2 min ago</p> -->
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <!-- <p class="app-notification__message">Mail server not working</p>
                                            <p class="app-notification__meta">5 min ago</p> -->
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a class="app-notification__item" href="javascript:;">
                                        <span class="app-notification__icon">
                                            <span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span>
                                        </span>
                                        <div>
                                            <!-- <p class="app-notification__message">Transaction complete</p>
                                            <p class="app-notification__meta">2 days ago</p> -->
                                        </div>
                                    </a>
                                </li>
                            </div>
                        </div>
                        <li class="app-notification__footer"><a href="#">See all notifications.</a></li>
                    </ul>
                </li>
                <!-- User Menu-->
                <li class="dropdown">
                    <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                    <ul class="dropdown-menu settings-menu dropdown-menu-right">
                        <li>
                            <!-- <a class="dropdown-item" href="#"><i class="fa fa-cog fa-lg"></i> Settings</a> -->
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'profile' %}"><i class="fa fa-user fa-lg"></i> Profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="fa fa-sign-out fa-lg"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </header>
        <!-- Sidebar menu-->
        <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
        <aside class="app-sidebar">
            <div class="app-sidebar__user">
                <!-- <img class="app-sidebar__user-avatar" src="{% static 'images/DP.jpg' %}" alt="User Image" height="50px" width="50px"/> -->
                <img class="app-sidebar__user-avatar" src="{{ user.profile_picture.url }}" alt="default.jpg" height="50px" width="50px"/>
                <div>
                    <!-- <p class="app-sidebar__user-name">Afiq Shafei</p> -->
                    <p class="app-sidebar__user-name">{{request.user.first_name}} {{request.user.last_name}}</p>
                    <!-- <p class="app-sidebar__user-designation">afiq.shafei@gmail.com</p> -->
                    <p class="app-sidebar__user-designation">{{request.user.email}}</p>
                </div>
            </div>
            <ul class="app-menu">
                <li>
                                                                            <!-- app-menu__icon fa fa-dashboard -->
                    <!-- <a class="app-menu__item active" href="{% url 'dashboard' %}"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a> -->
                </li>
                <li>
                                                                            <!-- app-menu__icon fa fa-calendar -->
                    <a class="app-menu__item" href="{% url 'calendarapp:calendar' %}"><i class="app-menu__icon fa fa-calendar"></i><span class="app-menu__label">Calendar</span></a>
                </li>
                <li class="treeview">
                                                                            <!-- app-menu__icon fa fa-th-list -->
                    <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Projects / Tasks</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                    <ul class="treeview-menu">
                        <!-- <li>
                            <a class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> Running</a>
                        </li>
                        <li>
                            <a class="treeview-item" href="{% url 'calendarapp:running_events' %}"><i class="icon fa fa-circle-o"></i> Upcoming</a>
                        </li> -->
                        <!-- <li>
                            <a class="treeview-item" href="{% url 'calendarapp:all_events' %}"><i class="icon fa fa-circle-o"></i> All</a>
                        </li>
                        <li> -->
                            <a class="treeview-item" href="{% url 'list_user_projects_and_tasks' %}"><i class="icon fa fa-circle-o"></i> All</a>
                        </li>
                        
                    </ul>
                </li>
                <li>
                    <!-- <a class="app-menu__item" href="#"><i class="app-menu__icon fa fa-file-code-o"></i><span class="app-menu__label">Docs</span></a> -->
                </li>
            </ul>
        </aside>
        <main class="app-content">
            <div class="app-title">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        <!-- Essential javascripts for application to work-->
        {% include 'base/js.html' %}
        {% block extrascripts %}
        {% endblock extrascripts %}
        <!-- Just added for the modal -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        
    </body>
</html>

templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script>
    $(document).ready(function() {
        $('.toast').toast('show');
    });
</script>



<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>