accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

calendarapp/urls.py
from django.urls import path

from . import views

app_name = "calendarapp"


urlpatterns = [
    path("", views.CalendarViewNew.as_view(), name="calendar"),
    path("calendar/", views.CalendarViewNew.as_view(), name="calendar"),
    # path("calendars/", views.CalendarView.as_view(), name="calendars"),     delete later
    path('delete_event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('next_week/<int:event_id>/', views.next_week, name='next_week'),
    path('next_day/<int:event_id>/', views.next_day, name='next_day'),
    path("event/new/", views.create_event, name="event_new"),
    path("event/edit/<int:pk>/", views.EventEdit.as_view(), name="event_edit"),
    path("event/<int:event_id>/details/", views.event_details, name="event-detail"),
    path(
        "add_eventmember/<int:event_id>", views.add_eventmember, name="add_eventmember"
    ),
    path(
        "event/<int:pk>/remove",
        views.EventMemberDeleteView.as_view(),
        name="remove_event",
    ),
    path("all-event-list/", views.AllEventsListView.as_view(), name="all_events"),
    path(
        "running-event-list/",
        views.RunningEventsListView.as_view(),
        name="running_events",
    ),
    # path('new_project/',views.ProjectCreateView.as_view() , name='new_project'),
   
]

project_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import DashboardView, ProfileView, UpdateProfileView, ProjectCreateView
from calendarapp.views import other_views
from calendarapp.views.other_views import CalendarView




urlpatterns = [
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("calendarapp.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='update_profile'),
    path('new_project/', ProjectCreateView.as_view(), name='new_project'),
    path('add_project/', other_views.add_project, name='add_project'),
    path('add_project/add_task', other_views.add_task, name="add_task"),    
    path('edit_project/<int:project_id>/', other_views.edit_project, name='edit_project'),
    path('delete_project/<int:project_id>/', other_views.delete_project, name='delete_project'),
    path('projects/', other_views.list_user_projects_and_tasks, name='list_user_projects_and_tasks'),
    path('projects/add_task/<int:project_id>/', other_views.add_task, name='add_task'),
    path('projects/edit_task/<int:task_id>/', other_views.edit_task, name='edit_task'),
    path('projects/delete_task/<int:task_id>/', other_views.delete_task, name='delete_task'),
    path('tasks/toggle/<int:task_id>/', other_views.toggle_task_completion, name='toggle_task_completion'),
    path('create_project_from_template/', other_views.create_project_from_template, name='create_project_from_template'),
    path('projects/add/', other_views.add_project, name='add_project'),
    # path('projects/<int:project_id>/save_as_template/', other_views.create_template_from_project, name='create_template_from_project'),
    # path('calendarView/', CalendarView.as_view, name='calendarView'),
    path('data/', other_views.templates_data, name='templates_data'),
    path('project/<int:project_id>/save_as_template/', other_views.save_project_as_template, name='save_project_as_template'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendarapp/models/event.py
from datetime import datetime
from django.db import models
from django.urls import reverse

from calendarapp.models import EventAbstract
from accounts.models import User


class EventManager(models.Manager):
    """ Event manager """

    def get_all_events(self, user):
        events = Event.objects.filter(user=user, is_active=True, is_deleted=False)
        return events

    def get_running_events(self, user):
        running_events = Event.objects.filter(
            user=user,
            is_active=True,
            is_deleted=False,
            end_time__gte=datetime.now().date(),
        ).order_by("start_time")
        return running_events


class Event(EventAbstract):
    """ Event model """

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="events")
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    objects = EventManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("calendarapp:event-detail", args=(self.id,))

    @property
    def get_html_url(self):
        url = reverse("calendarapp:event-detail", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

calendarapp/models/project.py
from django.db import models
from accounts.models import User

# class Project(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     title = models.CharField(max_length=255)
#     start_date = models.DateField()
#     end_date = models.DateField()

#     def __str__(self):
#         return self.title

class ProjectTemplate(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    duration = models.DurationField(null=True, blank=True)

    def __str__(self):
        return self.title

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)    
    start_date = models.DateField()
    template = models.ForeignKey(ProjectTemplate, on_delete=models.SET_NULL, null=True, blank=True)
    save_as_template = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Task(models.Model):
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    days_prior = models.IntegerField()
    # duration = models.DurationField()
    # duration = models.IntegerField(label='Number of Days', min_value=0)
    duration = models.IntegerField()
    is_actionable = models.BooleanField(default=True)
    email_notification = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
# added for the template
class TaskTemplate(models.Model):
    template = models.ForeignKey(ProjectTemplate, related_name='task_templates', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    days_prior = models.IntegerField()
    duration = models.IntegerField()

    def __str__(self):
        return self.name

templates/add_member.html
{% extends 'base.html' %}

{% block title %}
Add EventMember
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/add_task.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Project Planner | Add task {% endblock title %}

{% block breadcrumb %}
    <h2>Add Task</h2>
{% endblock breadcrumb %}

{% block content %}

<form method="post" action="{% url 'add_task' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_project" class="form-label">Project:</label>
        {{ form.project }}
    </div>
    <div class="mb-3">
        <label for="id_name" class="form-label">Name:</label>
        {{ form.name }}
    </div>
    <div class="mb-3">
        <label for="id_days_prior" class="form-label">Days Prior:</label>
        {{ form.days_prior }}
    </div>
    <div class="mb-3">
        <label for="id_duration" class="form-label">Duration:</label>
        {{ form.duration }}
    </div>
    <div class="mb-3 form-check">
        {{ form.is_actionable }}
        <label for="id_is_actionable" class="form-check-label">Is actionable</label>
    </div>
    <div class="mb-3 form-check">
        {{ form.email_notification }}
        <label for="id_email_notification" class="form-check-label">Email notification</label>
    </div>
    <button type="submit" name="submit" value="save" class="btn btn-primary">SAVE</button>
    <button type="submit" name="submit" value="save_add_another" class="btn btn-secondary">Save and add another</button>
    <button type="submit" name="submit" value="save_continue" class="btn btn-secondary">Save and continue editing</button>
</form>
{% endblock %}

templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/calender.css' %}">
  <title>Project Planner</title>
</head>
<body>

  {% block content %}

  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

templates/calendar.html
{% extends 'base.html' %}

{% block content %}
<div class="clearfix">
    <span class="left m-2" style="font-size: 20px;">Wellcome, {{ request.user }}</span>
    <a class="btn btn-info right" href="{% url 'accounts:signout' %}"> Sign Out</a>
	<a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ next_month }} "> Next Month >> </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:calendar' %}?{{ prev_month }}"> << Previous Month </a>
    <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_new' %}"> + New Event </a>
</div>
<div style="color: blueviolet;">
    {{ calendar }}
</div>
{% endblock %}

templates/delete_project.html
{% extends 'base/base.html' %}


{% block breadcrumb %}
  <h2>My Projects</h2>
{% endblock breadcrumb %}

{% block content %}
<div class="container">
  <h2>Are you sure you want to delete "{{ project.title }}"?</h2>
  <form action="{% url 'delete_project' project.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete this project</button>
    <a href="{% url 'list_user_projects_and_tasks' %}" class="btn btn-secondary">No, take me back</a>
  </form>
</div>
{% endblock content %}

templates/delete_task.html
{% extends 'base/base.html' %}

{% block breadcrumb %}
    <h2>Delete Task: </h2>
    <!-- <p>Are you sure you want to delete this task?</p> -->
{% endblock breadcrumb %}


{% block content %}
<!-- <h2>Delete Task: {{ task.name }}</h2> -->
<div class="tile">
    <div class="project-list">
        <p>Are you sure you want to delete this task?</p>
        <p>{{ task.name }}</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
            <a href="{% url 'list_user_projects_and_tasks' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/edit-project.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
  <h2>Edit Project</h2>
  <form action="{% url 'edit_project' project.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save changes</button>
    <a href="{% url 'list_user_projects_and_tasks' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock content %}

templates/edit_task.html
{% extends 'base/base.html' %}
{% block content %}
<h2>Edit Task: {{ task.name }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update Task</button>
</form>
{% endblock %}

templates/event-details.html
{% extends 'base.html' %}

{% block title %}
Event Details
{% endblock %}

{% block content %}
    <div class="container">
        <div class="clearfix">
            <a class="btn btn-primary left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
            <a class="btn btn-info right mr-2" href="{% url 'calendarapp:event_edit' event.pk %}"> Edit Event </a>
        </div>

        <div class="clearfix">
            <h3>Event Name: {{ event.title }}</h3>
            <p>From <span style="color: gray;">{{ event.start_time }}</span> To <span style="color: gray;">{{ event.end_time }}</span></p>
            <hr>
            <p>{{ event.description }}</p>
        </div>
        <hr>
        <div class="clearfix">
            <h4 class="left" > Members of this Event</h4>
            <a class="btn btn-success right" href="{% url 'calendarapp:add_eventmember' event.id %}"> Add Member </a>
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                  <th style="width: 10px">#</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for member in eventmember %}
                <tr role="row">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ member.user.first_name }} {{ member.user.last_name }}</td>
                    <td>{{ member.user.username }}</td>
                    <td>{{ member.user.email }}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'calendarapp:remove_event' member.id %}">Remove</a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
    </div>
{% endblock %}

templates/event.html
{% extends 'base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'calendarapp:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

templates/event_delete.html
<!-- templates/article_delete.html -->
{% extends 'base.html' %}

{% block title %}
Event Delete
{% endblock %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this event?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/template_data.html
{% if project_templates %}
  <select class="form-control" id="projectTemplate" name="template_id" required>
    <option value="" disabled selected>-- Select a template --</option>
    {% for template in project_templates %}
      <option value="{{ template.id }}">{{ template.title }}</option>
    {% endfor %}
  </select>
{% else %}
    <p class="text-muted">No templates available.</p>    
    <option value="" disabled>No templates available.</option>
{% endif %}


templates/user_projects_and_tasks.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
  Project planner | My Projects
{% endblock title  %}

{% block extracss %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
{% endblock extracss %}


{% block breadcrumb %}
  <h2>My Projects</h2>
{% endblock breadcrumb %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'path/to/your/datatables.css' %}">
<script type="text/javascript" charset="utf8" src="{% static 'path/to/your/datatables.js' %}"></script>

<div class="tile">
<div class="project-list">
    {% for project in user_projects %}
    <div class="project">
        <div class="project-header">
            <h3>{{ project.title }}</h3>
            <div class="project-actions">
                <!-- <a href="{% url 'edit_project' project.id %}" class="btn btn-primary">Edit</a> -->
                <form action="{% url 'delete_project' project.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>        
        <p>Start Date: {{ project.start_date }}</p>
        <!-- Just add for delete button  -->
        <!-- <a href="{% url 'edit_project' project.id %}" class="btn btn-primary">Edit</a>
        <form action="{% url 'delete_project' project.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form> -->
        <!-- <hr> -->
        {% for template in project_template %}
        <p>{{template.title }}</p>
        {% endfor %}
        <table id="taskTable_{{ forloop.counter }}" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Start On</th>
                    <th>Duration</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            
            <tbody>
                {% for task in project.tasks.all %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.start_date|date:"Y-m-d" }}</td>
                    <td>{{ task.duration }} days</td>
                    <td>
                        <form method="post" action="{% url 'toggle_task_completion' task.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm {% if task.is_actionable %}btn-success{% else %}btn-secondary{% endif %}">
                                {% if task.is_actionable %}Complete{% else %}Incomplete{% endif %}
                            </button>
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'edit_task' task.id %}" class="btn btn-sm btn-primary">Edit</a>
                        <a href="{% url 'delete_task' task.id %}" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>                
                {% endfor %}                  
            </tbody>
        </table>
        <div class="task-actions">
            <a href="{% url 'add_task' %}" class="btn btn-primary">Add Task</a>
            <form action="{% url 'save_project_as_template' project.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Save as Template" class="btn btn-primary">
            </form>            
        <!-- <hr> -->
        </div>
    </div>  
    <hr>    
    {% empty %}
        <div class="no-projects-message">
            <p>No project found.</p>
        </div>
    {% endfor %}
</div>
</div>

<script>
{% for project in user_projects %}
$(document).ready(function() {
    $('#taskTable_{{ forloop.counter }}').DataTable({
        "pagingType": "full_numbers",
        "order": []
    });
});
{% endfor %}
</script>
{% endblock %}
    